// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroEstudiante.Infrastructure.Persistance;

#nullable disable

namespace RegistroEstudiante.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925155236_AcademicEntities")]
    partial class AcademicEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "García",
                            Name = "Ana"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "López",
                            Name = "Carlos"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Martínez",
                            Name = "Laura"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rodríguez",
                            Name = "Diego"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Pérez",
                            Name = "Sofía"
                        });
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estudiante",
                            Name = "Student"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrador",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.StudentSubject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SubjectId", "UserId");

                    b.HasIndex("SubjectId", "ProfessorId");

                    b.HasIndex("UserId", "ProfessorId")
                        .IsUnique();

                    b.HasIndex("UserId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentSubjects", (string)null);
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_Credits", "[Credits] = 3");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Matemáticas",
                            Name = "Matemáticas",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Estadística",
                            Name = "Estadística",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Programación",
                            Name = "Programación",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Bases de datos",
                            Name = "Bases de datos",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Física",
                            Name = "Física",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Electrónica",
                            Name = "Electrónica",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Comunicación",
                            Name = "Comunicación",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Inglés",
                            Name = "Inglés",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Administración",
                            Name = "Administración",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreationDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credits = 3,
                            Description = "Emprendimiento",
                            Name = "Emprendimiento",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short>("IdentificationType")
                        .HasColumnType("smallint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("IdentificationType", "IdentificationNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.StudentSubject", b =>
                {
                    b.HasOne("RegistroEstudiante.Domain.Entities.User", "User")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroEstudiante.Domain.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId", "ProfessorId")
                        .HasPrincipalKey("Id", "ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Subject", b =>
                {
                    b.HasOne("RegistroEstudiante.Domain.Entities.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.User", b =>
                {
                    b.HasOne("RegistroEstudiante.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("RegistroEstudiante.Domain.Entities.User", b =>
                {
                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
